language: c++
dist: bionic
addons:
    apt:
        packages:
            - cmake
            - gcc-8
            - g++-8
            - liblua5.3-dev
            - libfltk1.3-dev
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-ttf-dev
            - libpng-dev
script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 -DCMAKE_BUILD_TYPE=Debug -DCMAKE_BUILD_PREFIX=.

notifications:
    email: false
