version: 'build-{build}'

image: Visual Studio 2017

platform: x64

environment:
    CMAKE_GENERATOR: -G"Visual Studio 15 2017 Win64"
    CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE="C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
    CMAKE_TARGET_TRIPLET: -DCMAKE_TARGET_TRIPLET=x64-windows
    VCPKG_DEFAULT_TRIPLET: x64-windows
 
configuration:
  - Release

install:
    - cmd: |-
        vcpkg install lua
        vcpkg install sdl2
        vcpkg install fltk
        vcpkg install opengl
        vcpkg install zlib
        vcpkg install libpng

before_build:
    - cmd: |-
        mkdir build
        cd build
        cmake --version
        cmake .. %CMAKE_GENERATOR% %CMAKE_TOOLCHAIN_FILE% %CMAKE_TARGET_TRIPLET%
        cmake --build . --target package --config Release

build_script:
    - echo "Done"

after_build:
    - echo "Done"

test_script:
    - echo "Done"

artifacts:
    - path: build\*.zip

deploy:
    provider: GitHub
    auth_token:
        secure: HHPH5otHDTeP2iU11PdRWnhpOMycDJ/n+NKC0xvSphvA4NLz41/rASWc1UseTQgU
    on:
        APPVEYOR_REPO_TAG: true
