version: 'build-{build}'

image: Visual Studio 2019


platform: x64

environment:
    VCPKG_INSTALLED_TOOLS_PATH: C:\Tools\vcpkg\installed\x64-windows-static\tools
    PATH: $(VCPKG_INSTALLED_TOOLS_PATH%);$(VCPKG_INSTALLED_TOOLS_PATH)\fltk;$(VCPKG_INSTALLED_TOOLS_PATH)\lua;$(PATH)
    CMAKE_GENERATOR: -G"Visual Studio 16 2019"
    CMAKE_TOOLCHAIN_FILE: -DCMAKE_TOOLCHAIN_FILE="C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake"
    CMAKE_CLANG_SETUP: -DCMAKE_C_COMPILER="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_CXX_COMPILER="C:\Program Files\LLVM\bin\clang-cl.exe" -DCMAKE_LINKER="C:\Program Files\LLVM\bin\lld-link.exe"
    CMAKE_VERBOSE_MAKEFILE: -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON
    VCPKG_DEFAULT_TRIPLET: x64-windows
    VCPKG_TARGET_TRIPLET: -DVCPKG_TARGET_TRIPLET=x64-windows-static

configuration:
    - Release

cache:
    - .git\lfs\objects -> appveyor.yml
    - C:\Tools\vcpkg\installed -> appveyor.yml

clone_script:
    - echo "Skip appveyor clone"

install:
    - cmd: |-
        vcpkg install lua:x64-windows-static
        vcpkg install sdl2:x64-windows-static
        vcpkg install sdl2-gfx:x64-windows-static
        vcpkg install sdl2-ttf:x64-windows-static
        vcpkg install sdl2-image:x64-windows-static
        vcpkg install fltk:x64-windows-static
        vcpkg install opengl:x64-windows-static
        vcpkg install zlib:x64-windows-static
        vcpkg install libpng:x64-windows-static
        vcpkg install lz4:x64-windows-static
        vcpkg install sqlite3:x64-windows-static
        git init %APPVEYOR_BUILD_FOLDER%
        cd %APPVEYOR_BUILD_FOLDER%
        git remote add origin https://github.com/%APPVEYOR_REPO_NAME%.git
        git fetch -q origin %APPVEYOR_REPO_COMMIT%
        git checkout -qf %APPVEYOR_REPO_COMMIT%

before_build:
    - cmd: |-
        git lfs prune
        mkdir build
        cd build
        cmake --version
        cmake .. %CMAKE_GENERATOR% %CMAKE_TOOLCHAIN_FILE% %CMAKE_CLANG_SETUP% %CMAKE_VERBOSE_MAKEFILE% %VCPKG_TARGET_TRIPLET%
        cmake --build . --target package --config Release

build_script:
    - echo "Done"

after_build:
    - echo "Done"

test_script:
    - echo "Done"

# artifacts:
#    - path: build\*.zip

on_finish:
    - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

deploy:
    provider: GitHub
    auth_token:
        secure: HHPH5otHDTeP2iU11PdRWnhpOMycDJ/n+NKC0xvSphvA4NLz41/rASWc1UseTQgU
    on:
        APPVEYOR_REPO_TAG: true
